serverPrefix: /translate

load:
  yaml:
    - file:databaseConfig.yml
    - file:myconf.yml
  properties:
    - file:resource.properties

server:
  port: 8098

logging:
  file: /home/wally/workspace/myprojects/logs/plan.log
  level:
    com:
      flyingrain:
        translate:
          plan:
            service:
              services:
                dao:
                  mapper: debug



