serverPrefix: /translate

spring:
  redis:
    password: 123456
    timeout: 0

load:
  properties:
    - file:authConf.properties
    - file:resource.properties
server:
  port: 8088

context:
  listener:
    classes: com.flyingrain.translate.framework.config.LoadAdditionalProperty
