serverPrefix: /translate

load:
  yaml:
    - file:databaseConfig.yml
  properties:
    - file:resource.properties

context:
  listener:
    classes: com.flyingrain.translate.framework.config.LoadAdditionalProperty

server:
  port: 8087