datasource:
  config:
    - sourceName: default
      userName: root
      password: Xtm123456!
      driveClass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.243.121.53:3306/userCenter?useUnicode=true&characterEncoding=UTF-8&useSSL=false

    - sourceName: test
      userName: root
      password: 123456
      driveClass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test2?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false