#服务前缀
serverPrefix: /translate
#需要装载的配置文件
load:
 properties:
   - file:resource.properties
 yaml:
   - file:myconf.yml


server:
  port: 8099

logging:
  file: /home/wally/workspace/myprojects/logs/restwapper.log




